"""add stock_after to inventory_movements

Revision ID: 70b0ef316b99
Revises: 8f4a2c1e5d90
Create Date: 2026-08-12 16:01:57.986106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b0ef316b99'
down_revision: Union[str, Sequence[str], None] = '8f4a2c1e5d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('stock_after', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movements', 'stock_after')
    # ### end Alembic commands ###
