"""initial schema datara mvp

Revision ID: edb68b91a3a6
Revises: 
Create Date: 2026-08-10 22:13:59.977431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'edb68b91a3a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='conversationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_business_id'), 'ai_conversations', ['business_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('business_configurations',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('safety_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lead_time', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_configurations_business_id'), 'business_configurations', ['business_id'], unique=True)
    op.create_table('business_health_assessments',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('health_status', sa.Enum('SEHAT', 'PERLU_PERHATIAN', 'BERISIKO', 'INSUFFICIENT_DATA', name='healthstatus'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_health_assessments_business_id'), 'business_health_assessments', ['business_id'], unique=False)
    op.create_table('business_targets',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('target_type', sa.Enum('SALES', 'PROFIT', name='targettype'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('period_type', sa.Enum('MONTHLY', name='periodtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='targetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_targets_business_id'), 'business_targets', ['business_id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_user_id'), 'businesses', ['user_id'], unique=True)
    op.create_table('decisions_applied',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('recommendation_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('type', sa.Enum('PRICING', 'RESTOCK', name='decisionappliedtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('metrics_before', sa.JSON(), nullable=True),
    sa.Column('metrics_after', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('IMPROVED', 'FLAT', 'REGRESSED', name='decisionappliedstatus'), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_applied_business_id'), 'decisions_applied', ['business_id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_business_id'), 'forecast_results', ['business_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_product_id'), 'forecast_results', ['product_id'], unique=False)
    op.create_table('growth_recommendations',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.Enum('PRICING', 'SALES', 'INVENTORY', 'PROFITABILITY', name='growthcategory'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='growthpriority'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DISMISSED', 'EXPIRED', name='growthstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_recommendations_business_id'), 'growth_recommendations', ['business_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_inventory_items_business_id'), 'inventory_items', ['business_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('movement_type', sa.Enum('RESTOCK', 'SALE', 'ADJUSTMENT', 'WASTE', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('movement_date', sa.DateTime(), nullable=False),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_business_id'), 'inventory_movements', ['business_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_table('operating_expenses',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('expense_type', sa.Enum('RENT', 'FIXED_SALARY', 'ADMINISTRATIVE', 'OTHER', name='expensetype'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_expenses_business_id'), 'operating_expenses', ['business_id'], unique=False)
    op.create_table('pricing_recommendations',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_hpp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estimated_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DISMISSED', 'EXPIRED', name='recommendationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_recommendations_business_id'), 'pricing_recommendations', ['business_id'], unique=False)
    op.create_index(op.f('ix_pricing_recommendations_product_id'), 'pricing_recommendations', ['product_id'], unique=False)
    op.create_table('product_costs',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('cost_type', sa.Enum('RAW_MATERIAL', 'PACKAGING', 'DIRECT_LABOR', 'PRODUCTION_OVERHEAD', name='costtype'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_costs_product_id'), 'product_costs', ['product_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_table('restock_recommendations',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forecasted_demand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('safety_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommended_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DISMISSED', 'EXPIRED', name='recommendationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restock_recommendations_business_id'), 'restock_recommendations', ['business_id'], unique=False)
    op.create_index(op.f('ix_restock_recommendations_product_id'), 'restock_recommendations', ['product_id'], unique=False)
    op.create_table('sales_transaction_items',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unit_hpp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_transaction_items_product_id'), 'sales_transaction_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_transaction_items_transaction_id'), 'sales_transaction_items', ['transaction_id'], unique=False)
    op.create_table('sales_transactions',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index(op.f('ix_sales_transactions_business_id'), 'sales_transactions', ['business_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_transactions_business_id'), table_name='sales_transactions')
    op.drop_table('sales_transactions')
    op.drop_index(op.f('ix_sales_transaction_items_transaction_id'), table_name='sales_transaction_items')
    op.drop_index(op.f('ix_sales_transaction_items_product_id'), table_name='sales_transaction_items')
    op.drop_table('sales_transaction_items')
    op.drop_index(op.f('ix_restock_recommendations_product_id'), table_name='restock_recommendations')
    op.drop_index(op.f('ix_restock_recommendations_business_id'), table_name='restock_recommendations')
    op.drop_table('restock_recommendations')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_costs_product_id'), table_name='product_costs')
    op.drop_table('product_costs')
    op.drop_index(op.f('ix_pricing_recommendations_product_id'), table_name='pricing_recommendations')
    op.drop_index(op.f('ix_pricing_recommendations_business_id'), table_name='pricing_recommendations')
    op.drop_table('pricing_recommendations')
    op.drop_index(op.f('ix_operating_expenses_business_id'), table_name='operating_expenses')
    op.drop_table('operating_expenses')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_business_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_items_business_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_growth_recommendations_business_id'), table_name='growth_recommendations')
    op.drop_table('growth_recommendations')
    op.drop_index(op.f('ix_forecast_results_product_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_business_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_decisions_applied_business_id'), table_name='decisions_applied')
    op.drop_table('decisions_applied')
    op.drop_index(op.f('ix_businesses_user_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_business_targets_business_id'), table_name='business_targets')
    op.drop_table('business_targets')
    op.drop_index(op.f('ix_business_health_assessments_business_id'), table_name='business_health_assessments')
    op.drop_table('business_health_assessments')
    op.drop_index(op.f('ix_business_configurations_business_id'), table_name='business_configurations')
    op.drop_table('business_configurations')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_conversations_business_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
